### ISSUE TITLE
sandworm: init.lua:101: attempt to index local 'physics' (a nil value)

### ISSUE THREAD

**Issue by verymilan** [blert2112/mobs_more_monsters#1]
Hi, there is a small issue on the sandworm:

```
    init.lua:101: attempt to index local 'physics' (a nil value)
```

I am not sure if it possible to change that without complex changes on the code, maybe someone with more experience then me should do that. It happens rare and random and it not really reproducable.
Also itemstack:take_item(1) does not work.

**Comment by blert2112** [comment]
Should be fixed. Thanks for the 'heads up'.

**Comment by verymilan** [comment]
thank you :+1:
